version: '2'
services:
    exam-app:
        image: exam
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=exam-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    exam-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: exam-cassandra
    exam-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=exam-cassandra
    exam-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: exam-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
